"""create tables

Revision ID: 2951e86d15c3
Revises: 4da828e93c8f
Create Date: 2025-08-30 08:27:29.099840

"""
from alembic import op
import sqlalchemy as sa

# Revision identifiers, used by Alembic.
revision = '2951e86d15c3'
down_revision = '4da828e93c8f'
branch_labels = None
depends_on = None


def upgrade():
    """Apply database changes"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    """Revert database changes"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
